### ISSUE TITLE
Capacitor sync fails: no compatible versions found for pod CapacitorCommunityFileOpener

### ISSUE THREAD

**Issue by sanderschnydrig** [capacitor-community/file-opener#8] opened 2022-10-19 09:30 UTC
**Describe the bug**
Capacitor sync cannot find a compatible version for pod "CapacitorCommunityFileOpener"

**To Reproduce**
1. `npm install @capacitor-community/file-opener`
2. `npx cap sync`

**Expected behavior**
I expected the Capacitor sync to throw no errors after installing this plugin.

**Screenshots**
![Screenshot 2022-10-19 at 11 28 06](https://user-images.githubusercontent.com/79841899/196653271-58ca87b3-6382-4531-aa95-99f9d21d7b0b.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.4

**Additional information**
We would really like to keep our minimum deployment target for out application as it is the default for our Capacitor v3 app and was set when we created the Capacitor v3 app.

Everywhere in our project.pbxproj:
`IPHONEOS_DEPLOYMENT_TARGET = 12.0;`
Looks like the version set in the podspec is `s.ios.deployment_target  = '13.0'`

We don't need this plugin for iOS at the moment so is there a way to only use it for Android?

**Comment by sanderschnydrig** [comment] 2022-10-19 09:55
As a temporary workaround we are replacing the CapacitorCommunityFileOpener.podspec file before doing a capacitor sync, with `s.ios.deployment_target = '12.0'` set to a compatible version.

**Comment by ryaa** [comment] 2022-10-19 12:01
> Looks like the version set in the podspec is s.ios.deployment_target = '13.0'

Yes. This is the reason for the error.

> We don't need this plugin for iOS at the moment so is there a way to only use it for Android?

I have not tried it myself but **includePlugins** property for the specific platform should help.
Please see includePlugins for iOS here https://capacitorjs.com/docs/config

Another option to fix the problem is to use https://github.com/ds300/patch-package (I use it a lot and find it to be a really helpful tool) to automatically apply your workaround when npm packages are installed.

Let me know if this worked for you. For now, i will close the issue since no changes, related to this issue are planned.

**Closed as completed by ryaa** 2022-10-19 12:01 UTC
Labels: wontfix
