### ISSUE TITLE
Gradle build failed: cannot access ContentProvider

### ISSUE THREAD

**Issue by sanderschnydrig** [capacitor-community/file-opener#9] opened 2022-10-19 11:22 UTC
**Describe the bug**
Gradle build fails with the following error message:
```console
/Users/sander/Fork/pomona-app/node_modules/@capacitor-community/file-opener/android/src/main/java/com/ryltsov/alex/plugins/file/opener/FileOpenerProvider.java:6: error: cannot access ContentProvider
public class FileOpenerProvider extends androidx.core.content.FileProvider {}
       ^
  class file for android.content.ContentProvider not found
```

**To Reproduce**
1. `npm install @capacitor-community/file-opener` inside a capacitor v3 project
2. `npx cap sync android`
3. Make Capacitor build
4. Open Android Studio and try to build app on a simulator (Pixel 5 API 32)

**Expected behavior**
I expect there to be no gradle errors when building the app with this plugin

**Desktop (please complete the following information):**
 - OS: MacOs Mopnterey 12.4

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - API: 32

**Additional context**
We are using `npx jetify` for androidX compatibility of some of our used dependencies

gradle.properties:
```properties
# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

org.gradle.java.home=/Applications/Android\ Studio.app/Contents/jre/Contents/Home

export JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/Contents/Home
```

variables.gradle:
```gradle
ext {
    minSdkVersion = 22
    compileSdkVersion = 30
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '7.0.0'
}
```

build.gradle:
```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.google.gms:google-services:4.3.10'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

app/build.gradle:
```gradle
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation("androidx.appcompat:appcompat:$androidxAppCompatVersion") {
        force = true
    }
    implementation project(':capacitor-android')
    implementation 'androidx.webkit:webkit:1.4.0'
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
    implementation project(':capacitor-cordova-android-plugins')
    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:28.4.2')
    // Declare the dependencies for the Firebase Cloud Messaging and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    // implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-analytics'
    implementation "com.google.firebase:firebase-iid"
}
```

**Comment by ryaa** [comment] 2022-10-19 12:24
This issue may need more information before it can be addressed. Specifically, can you please provide a sample application (repository in the GitHub) that demonstrates the issue. Thank you.

**Comment by sanderschnydrig** [comment] 2022-10-20 08:50
@ryaa I made a sample project in which I was able to reproduce this issue (and the other one as well if you do `npx cap sync ios`):

https://github.com/sanderschnydrig/fileOpenerSample

Hope this helps.

**Comment by ryaa** [comment] 2022-10-20 16:36
> @ryaa I made a sample project in which I was able to reproduce this issue (and the other one as well if you do `npx cap sync ios`):
> 
> https://github.com/sanderschnydrig/fileOpenerSample
> 
> Hope this helps.

I don't see capacitor, android platform and file-opener plugin in the project. Can you please update the repository with the required source code/instructions to reproduce the problem. Thank you.

**Comment by ryaa** [comment] 2022-10-20 16:37
@sanderschnydrig I have also provided my feedback on the issue for the ios platform - see https://github.com/capacitor-community/file-opener/issues/8#issuecomment-1283899446

**Comment by sanderschnydrig** [comment] 2022-10-21 07:53
@ryaa my excuses, I forgot to push those. The repository should contain all the necessary files now.

**Comment by aaronbach** [comment] 2022-10-21 15:23
I am facing the same problem, after switching from `cordova-plugin-file-opener2`: https://github.com/pwlin/cordova-plugin-file-opener2

I am also using capacitor3 and needed to run `npx jetifier` with `cordova-plugin-file-opener2`

**Comment by ryaa** [comment] 2022-10-22 05:23
> @ryaa my excuses, I forgot to push those. The repository should contain all the necessary files now.

Thanks for the update. I pulled the latest changes, then run `npm install` and then `npx ng build` and got the below error

```
alexs-mbp:main alexryltsov$ npx ng build
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './symbols'
Require stack:
- /Users/alexryltsov/Git/FILE-OPENER-SAMPLE/main/node_modules/ansi-colors/index.js
- /Users/alexryltsov/Git/FILE-OPENER-SAMPLE/main/node_modules/@angular/cli/utilities/color.js
- /Users/alexryltsov/Git/FILE-OPENER-SAMPLE/main/node_modules/@angular/cli/lib/init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at create (/Users/alexryltsov/Git/FILE-OPENER-SAMPLE/main/node_modules/ansi-colors/index.js:171:20)
    at Object.<anonymous> (/Users/alexryltsov/Git/FILE-OPENER-SAMPLE/main/node_modules/ansi-colors/index.js:176:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/alexryltsov/Git/FILE-OPENER-SAMPLE/main/node_modules/ansi-colors/index.js',
    '/Users/alexryltsov/Git/FILE-OPENER-SAMPLE/main/node_modules/@angular/cli/utilities/color.js',
    '/Users/alexryltsov/Git/FILE-OPENER-SAMPLE/main/node_modules/@angular/cli/lib/init.js'
  ]
}
```

Can you please check if the build work? and can you please provide the detailed build and run/deploy instructions to reproduce your problem?

**Comment by ryaa** [comment] 2022-10-22 13:10
The problem is that your android project uses an old version of **gradle/gradle plugin** and this causes this problem. According to the capacitor docs it should be updated to a more recent version that you use now - see section **Android Studio Plugin Update Recommended** here https://capacitorjs.com/docs/v2/android/updating.

You can update gradle/gradle plugin as describe in the link above or accept this [PR](https://github.com/sanderschnydrig/fileOpenerSample/pull/1) and test it.

Please let me know if this fixes your problem.

**Comment by luke-rogers** [comment] 2022-10-24 08:57
I ran into this issue and can confirm the changes in the [PR](https://github.com/sanderschnydrig/fileOpenerSample/pull/1) resolved them for me.

Thanks!

**Comment by sanderschnydrig** [comment] 2022-10-25 07:31
I can confirm its working on my side as well. It's weird that the configuration is wrong for a new capacitor project I created following their own guide. Thanks a bunch!

**Comment by ryaa** [comment] 2022-10-25 08:16
Closing as this is not the plugin problem.

**Closed as completed by ryaa** 2022-10-25 08:16 UTC
Labels: bug, wontfix
