### ISSUE TITLE
File-Opener does not work in Ionic Vuejs Android App 

### ISSUE THREAD

**Issue by cbsmerveguel** [capacitor-community/file-opener#58] opened 2024-05-11 18:43 UTC
Dear capacitor-community gurus,

The file-opener does not work on Android on an Ionic Vuejs application with the following versions. (READ_EXTERNAL_STORAE permission is added to the Manifest)

![image](https://github.com/capacitor-community/file-opener/assets/127400927/b68903fa-5690-47cc-a11e-71d275b3d3e6)

    "@ionic/vue": "^7.0.0",
    "vue": "^3.3.0",
    "@capacitor-community/file-opener": "^6.0.0"

![image](https://github.com/capacitor-community/file-opener/assets/127400927/030376d3-caaf-40cc-b666-f257ba643bdb)

Could you kindly share your comments?

**Comment by ryaa** [comment] 2024-05-13 04:00
This issue needs more information before it can be addressed. In particular, the reporter needs to provide a minimal sample app that demonstrates the issue. If no sample app is provided within 15 days, the issue will be closed.
Please see the Contributing Guide for [how to create a Sample App](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).
Thank you

**Comment by ryaa** [comment] 2024-05-23 10:20
The problem is not reproducible and there is no feedback from @cbsmerveguel. Closing as invalid

**Closed as completed by ryaa** 2024-05-23 10:20 UTC
Labels: invalid

**Comment by lucafulgenzi** [comment] 2025-01-27 09:33
@cbsmerveguel I am in the same situation as you, but with Angular, did you then solve the problem?

**Comment by ryaa** [comment] 2025-01-27 13:02
> [@cbsmerveguel](https://github.com/cbsmerveguel) I am in the same situation as you, but with Angular, did you then solve the problem?

I have added the sample app showing file opener usage (see https://github.com/capacitor-community/file-opener/tree/master/example-app). Is the problem reproducible in this example app?

**Comment by lucafulgenzi** [comment] 2025-01-30 15:24
In the end I simply used the latest version (even with an older version of angular/ionic) and everything worked correctly.
